branches:
  only:
  - develop
  - master

language: python
python:
  - "3.5"
  - "3.6"

os:
  - linux
  - osx

osx_image:
  xcode10.1

install:
  - pip install ddt
  - python setup.py install

script: 
  python setup.py test
