package:
  name: louvain
  version: "0.5.3"

source:
  fn: louvain-0.5.3.tar.gz
  url: https://pypi.python.org/packages/61/0f/ec441b9d8ccd951dbd1ec0330cafffade67f4ebef6847ff7e5b4d004c4c9/louvain-0.5.3.tar.gz
  md5: ae305e69f19d5ab2ccd11510fec52cb4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - louvain = louvain:main
    #
    # Would create an entry point called louvain that calls louvain.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-igraph >=0.7.1.0

  run:
    - python
    - python-igraph >=0.7.1.0

test:
  # Python imports
  imports:
    - louvain

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/vtraag/louvain-igraph
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Louvain is a general algorithm for methods of community detection in large networks.'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
